WebApp/Areas/MasterAdmin/Controllers/LocalApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Entities.HomeEntities;
using Data.UnitOfWork;
using System.ComponentModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using ViewModels.DynamicAccess;
using ViewModels.HomeViewModels;
using System.IO;

namespace WebApp.Areas.MasterAdmin.Controllers
{
    [Area("MasterAdmin")]
    [DisplayName("مدیریت فاوا|لیست لینکهای صفحه اصلی")]

    public class LocalApplicationsController : Controller
    {
        private readonly IUnitOfWork _Uw;
        private readonly IWebHostEnvironment _env;

        public LocalApplicationsController(IUnitOfWork Uw, IWebHostEnvironment env)
        {
            _Uw = Uw;
            _env = env;
        }

        //[Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("مشاهده لینکها ")]
        public async Task<IActionResult> Index()
        {
            var lp = await _Uw.BaseRepository<LocalApplications>().FindAllAsync();
            List<LocalApplicationsIndexedViewModels> model = new List<LocalApplicationsIndexedViewModels>();
            

            foreach (var item in lp)
            {
                LocalApplicationsIndexedViewModels lvm = new LocalApplicationsIndexedViewModels
                {
                    //DeleteBy = item.DeleteBy,
                    //Description = item.Description,
                    //DeleteDate = item.DeleteDate,
                    //InsertBy = item.InsertBy,
                    Id = item.LocalAppID,
                    //InsertDate = item.InsertDate,
                    //IsActive = item.IsActive,
                    IsLocalApp = item.IsLocalApp,
                    Title = item.Title,
                    //UpdateBy = item.UpdateBy,
                    //UpdateDate = item.UpdateDate,
                    ApplicationPath = item.ApplicationPath,

                };

                model.Add(lvm);
            }


            return View(model);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localApplications = await _Uw.BaseRepository<LocalApplications>().FindByIdAsync(id);
            if (localApplications == null)
            {
                return NotFound();
            }

            return View(localApplications);
        }

        //[Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("ایجاد لینک")]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LocalApplicationsCreateViewModels vm)
        {
            //byte[] image = null;
            if (ModelState.IsValid)
            {
                string FileExtension = Path.GetExtension(vm.File.FileName);
                string NewFileName = String.Concat(Guid.NewGuid().ToString(), FileExtension);
                var path = $"{_env.WebRootPath}/images/LocalApplications/{NewFileName}";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await vm.File.CopyToAsync(stream);
                }

                vm.ImageName = NewFileName;
                LocalApplications model = new LocalApplications
                {
                    Title = vm.Title.Trim(),
                    //InsertBy = "",
                    //InsertDate = DateTime.Now,
                    //Description = vm.Description,
                    //IsActive = true,
                    IsLocalApp = vm.IsLocalApp,
                    ApplicationPath = vm.ApplicationPath,
                };

                if (vm.ImageName != null)
                {
                    model.ImageName = vm.ImageName;
                }

                //if (vm.Image != null)
                //{
                //    using (var memorySteam = new MemoryStream())
                //    {
                //        await vm.Image.CopyTo(memorySteam);
                //        model.Image = memorySteam.ToArray();
                //    }
                //}

                await _Uw.BaseRepository<LocalApplications>().CreateAsync(model);
                await _Uw.Commit();
                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }

        //[Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("ویرایش لینک")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lp = await _Uw.BaseRepository<LocalApplications>().FindByIdAsync(id);
            if (lp == null)
            {
                return NotFound();
            }
            LocalApplicationsEditViewModels vm = new LocalApplicationsEditViewModels
            {
                Title = lp.Title.Trim(),
                //InsertBy = lp.InsertBy,
                //InsertDate = lp.InsertDate,
                //Description = lp.Description,
                //IsActive = lp.IsActive,
                IsLocalApp = lp.IsLocalApp,
                ApplicationPath = lp.ApplicationPath,
            };

            

            return View(vm);
        }

        // POST: Fava/LocalApplications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LocalApplicationsEditViewModels model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            var me = await _Uw.BaseRepository<LocalApplications>().FindByIdAsync(id);
            if (me == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    //me.UpdateBy = User.ToString();
                    //me.UpdateDate = DateTime.Now;
                    //me.IsActive = model.IsActive;
                    me.Title = model.Title;
                    me.Description = model.Description;
                    me.IsLocalApp = model.IsLocalApp;
                    me.ApplicationPath = model.ApplicationPath;

                    _Uw.BaseRepository<LocalApplications>().Update(me);
                    await _Uw.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalApplicationsExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }


        //[Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("حذف لینک")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localApplications = await _Uw.BaseRepository<LocalApplications>().FindByIdAsync(id);
            if (localApplications == null)
            {
                return NotFound();
            }

            return View(localApplications);
        }

        // POST: Fava/LocalApplications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var localApplications = await _Uw.BaseRepository<LocalApplications>().FindByIdAsync(id);
            _Uw.BaseRepository<LocalApplications>().Delete(localApplications);
            await _Uw.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool LocalApplicationsExists(int id)
        {
            if (_Uw.BaseRepository<LocalApplications>().FindByIdAsync(id) != null)
            {
                return true;
            }
            return false; ;
        }
    }
}

WebApp/Areas/MasterAdmin/Pages/Doctor/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Data;
using Entities.HISEntities.PractitionerEntity;
using Data.UnitOfWork;

namespace WebApp.Areas.MasterAdmin.Pages.Doctor
{
    public class CreateModel : PageModel
    {
        private readonly IUnitOfWork _uw;

        public CreateModel(IUnitOfWork uw)
        {
            _uw = uw;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Doctors DoctorModels { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //_context.Doctors.Add(Doctors);
            //await _context.SaveChangesAsync();

            await _uw.BaseRepository<Doctors>().CreateAsync(DoctorModels);
            await _uw.Commit();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Areas/MasterAdmin/Pages/Doctor/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Data;
using Entities.HISEntities.PractitionerEntity;

namespace WebApp.Areas.MasterAdmin.Pages.Doctor
{
    public class DeleteModel : PageModel
    {
        private readonly Data.PortalDbContext _context;

        public DeleteModel(Data.PortalDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Doctors Doctors { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Doctors = await _context.Doctors.FirstOrDefaultAsync(m => m.DoctorsID == id);

            if (Doctors == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Doctors = await _context.Doctors.FindAsync(id);

            if (Doctors != null)
            {
                _context.Doctors.Remove(Doctors);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Areas/MasterAdmin/Pages/Doctor/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Data;
using Entities.HISEntities.PractitionerEntity;

namespace WebApp.Areas.MasterAdmin.Pages.Doctor
{
    public class DetailsModel : PageModel
    {
        private readonly Data.PortalDbContext _context;

        public DetailsModel(Data.PortalDbContext context)
        {
            _context = context;
        }

        public Doctors Doctors { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Doctors = await _context.Doctors.FirstOrDefaultAsync(m => m.DoctorsID == id);

            if (Doctors == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApp/Areas/UserPanel/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Entities.HISEntities.PractitionerEntity;

namespace WebApp.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class DoctorsController : Controller
    {
        private readonly PortalDbContext _context;

        public DoctorsController(PortalDbContext context)
        {
            _context = context;
        }

        // GET: UserPanel/Doctors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Doctors.ToListAsync());
        }

        // GET: UserPanel/Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorsID == id);
            if (doctors == null)
            {
                return NotFound();
            }

            return View(doctors);
        }

        // GET: UserPanel/Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserPanel/Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Doctors doctors)
        {
            if (ModelState.IsValid)
            {
                var dc = new Doctors
                {
                    PractitionerJobCategory = doctors.PractitionerJobCategory,
                    FirstName = doctors.FirstName,
                    LastName = doctors.LastName,
                    Gender = doctors.Gender,
                    RegisterationNo = doctors.RegisterationNo,
                };
                _context.Add(doctors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctors);
        }

        // GET: UserPanel/Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors.FindAsync(id);
            if (doctors == null)
            {
                return NotFound();
            }
            return View(doctors);
        }

        // POST: UserPanel/Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorsID,PractitionerSpeciality,PractitionerJobCategory,FirstName,LastName,IsActive,Gender,RegisterationNo")] Doctors doctors)
        {
            if (id != doctors.DoctorsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorsExists(doctors.DoctorsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctors);
        }

        // GET: UserPanel/Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorsID == id);
            if (doctors == null)
            {
                return NotFound();
            }

            return View(doctors);
        }

        // POST: UserPanel/Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctors = await _context.Doctors.FindAsync(id);
            _context.Doctors.Remove(doctors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorsExists(int id)
        {
            return _context.Doctors.Any(e => e.DoctorsID == id);
        }
    }
}

WebApp/Views/Shared/_Admin.cshtml
<!doctype html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>پرتال داخلی</title>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    <script src="~/js/cheknationalcode.js"></script>
    <link rel="stylesheet" href="/vendor/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="/vendor/font-awesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/jquery.bonsai.css">
    <link href="/select2/dist/css/select2.css" rel="stylesheet" />
    <link href="/css/bootstrap-fileinput.css" rel="stylesheet" />
    <link href="/css/TreeView.css" rel="stylesheet" />
</head>
<body class="sidebar-fixed header-fixed" >
    <div class="page-wrapper">
        <nav class="navbar page-header">
            <div>
                <a href="#" class="btn btn-link sidebar-mobile-toggle d-md-none mr-auto">
                    <i class="fa fa-bars"></i>
                </a>
                <a class="navbar-brand" href="#">
                    <img src="/images/logo-header.png" alt="logo" height="45">
                    پنل مرکزی
                </a>
                <a href="#" class="btn btn-link sidebar-toggle d-md-down-none">
                    <i class="fa fa-bars"></i>
                </a>
            </div>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="/images/avatar-1.png" class="avatar avatar-sm" alt="logo">
                        <span class="small ml-1 d-md-down-none">حمزه شاکریان</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header">حساب کاربری</div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-user"></i> پروفایل
                        </a>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-lock"></i> خروج
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        <div class="main-container">
            <div class="sidebar">
                <nav class="sidebar-nav">
                    <ul class="nav">
                        <li class="nav-title">پنل مدیریت</li>
                        <li class="nav-item">
                            <a href="index.html" class="nav-link">
                                <i class="icon icon-speedometer"></i> داشبورد
                            </a>
                        </li>

                        @*<li class="nav-item">
                                <a href="layouts-normal.html" class="nav-link">
                                    <i class="icon icon-target"></i> مشاهده مراکز
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="layouts-fixed-sidebar.html" class="nav-link">
                                    <i class="icon icon-target"></i> افزودن مرکز جدید
                                </a>
                            </li>*@

                        @await Html.PartialAsync("_AdminMenu")
                    </ul>
                </nav>
            </div>
            <div class="content">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div id="Modal1" class="modal fade bd-example-modal-lg" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">    +++   </h4>
                </div>
                <div class="modal-body">
                    <p> --- </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal" onclick="GetPatientID()" >تایید</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" >بستن</button>
                </div>
            </div>

        </div>
    </div>




    <script src="/vendor/popper.js/popper.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/vendor/chart.js/chart.min.js"></script>
    <script src="/js/carbon.js"></script>
    <script src="/js/demo.js"></script>

    <script src="/select2/dist/js/select2.min.js"></script>
    <script src="/select2/dist/js/select2.full.js"></script>
    <script src="/js/bootstrap-fileinput.js"></script>
    <script src="/js/TreeView.js"></script>

    <script>

        // for select2
        $(".select2").select2({
            placeholder: "انتخاب کنید"
        });

        // for TreeView
        $('.demo1').bonsai();

    </script>

    @RenderSection("Scripts", false)
</body>
</html>

WebApp/Views/Shared/_AdminMenu.cshtml
@using Common
@addTagHelper*,Portal

<li class="nav-item nav-dropdown">
    <a href="#" class="nav-link nav-dropdown-toggle">
        <i class="icon icon-target"></i> مدیریت دسترسی ها <i class="fa fa-caret-left"></i>
    </a>
    <ul class="nav-dropdown-items">
        <ul>
            <li class="nav-item">
                <security-trimming asp-action="Create" asp-controller="RolesManager" asp-area="Admin">
                    <a class="nav-link" asp-action="Index" asp-controller="RolesManager" asp-area="Admin">
                        <i class="ni ni-settings-gear-65 text-suceess"></i> تعریف نقش
                    </a>
                </security-trimming>
            </li>
            <li class="nav-item">
                <security-trimming asp-action="Index" asp-controller="UserManager" asp-area="Admin">
                    <a class="nav-link" asp-action="Index" asp-controller="UserManager" asp-area="Admin">
                        <i class="ni ni-settings-gear-65 text-suceess"></i> تعریف کاربران
                    </a>
                </security-trimming>
            </li>


            @*<li class="nav-item">
                    <a class="nav-link" asp-action="Profile" asp-controller="Manage" asp-route-userId="@User.Identity.GetUserId()">
                        <i class="ni ni-circle-08 text-pink"></i> نمایه من
                    </a>
                </li>*@

        </ul>
    </ul>
</li>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LocalApplicationsPartial.cshtml
@model IEnumerable<Entities.HomeEntities.LocalApplications>



<style>
    .card-custom {
        max-width: 150px;
    }

    .imgx {
        width: 120px;
        height: 120px;
        padding: 4px 4px 4px 4px;
    }
</style>

<div class="row justify-content-center">
    @foreach (var item in Model)
    {
        bool islocalapp = item.IsLocalApp;
        string apppath = (item.IsLocalApp ? "webrun:" + item.ApplicationPath : item.ApplicationPath);
        <div class="card card-custom mx-1 mb-3">
            <a href="@apppath" target="_blank" class="text-center">
                <img src="~/images/LocalApplications/@item.ImageName" alt="" class="card-img imgx" />
                <br />
                @item.Title
            </a>
            <p class="text-center text-info">
                @item.Description
            </p>

        </div>
    }
</div>

WebApp/Views/Shared/_MasterAdmin.cshtml
@using Common
@addTagHelper*,Portal

<li class="nav-item nav-dropdown">
    <a href="#" class="nav-link nav-dropdown-toggle">
        <i class="icon icon-target"></i> مدیریت صفحه اصلی <i class="fa fa-caret-left"></i>
    </a>
    <ul class="nav-dropdown-items">
        <ul>
            <li class="nav-item">
                <security-trimming asp-action="Create" asp-controller="LocalApplications" asp-area="MasterAdmin">
                    <a class="nav-link" asp-action="Index" asp-controller="LocalApplications" asp-area="MasterAdmin">
                        <i class="ni ni-settings-gear-65 text-suceess"></i> ایجاد لینک سامانه ها
                    </a>
                </security-trimming>
            </li>
       


            @*<li class="nav-item">
            <a class="nav-link" asp-action="Profile" asp-controller="Manage" asp-route-userId="@User.Identity.GetUserId()">
                <i class="ni ni-circle-08 text-pink"></i> نمایه من
            </a>
        </li>*@

        </ul>
    </ul>
</li>

<li class="nav-item nav-dropdown">
    <a href="#" class="nav-link nav-dropdown-toggle">
        <i class="icon icon-target"></i> مدیریت سیستم <i class="fa fa-caret-left"></i>
    </a>
    <ul class="nav-dropdown-items">
        <ul>
            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-target"></i> مدیریت پزشکان <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <ul>
                        <li class="nav-item">
                            <security-trimming asp-action="Index" asp-controller="Patients" asp-area="UserPanel">
                                <a class="nav-link" asp-action="Index" asp-controller="Users" asp-area="UserPanel">
                                    <i class="ni ni-settings-gear-65 text-suceess"></i> پزشک همکار
                                </a>
                            </security-trimming>
                        </li>
                        <li class="nav-item">
                            <security-trimming asp-action="Create" asp-controller="Patients" asp-area="Admin">
                                <a class="nav-link" asp-action="Index" asp-controller="Doctors" asp-area="UserPanel">
                                    <i class="ni ni-settings-gear-65 text-suceess"></i> پزشک غیر همکار
                                </a>
                            </security-trimming>
                        </li>
                    </ul>
                </ul>
            </li>
        </ul>
    </ul>

    <ul class="nav-dropdown-items">
        <ul>
            <li class="nav-item nav-dropdown">
                <a href="#" class="nav-link nav-dropdown-toggle">
                    <i class="icon icon-target"></i> مدیریت مکان <i class="fa fa-caret-left"></i>
                </a>
                <ul class="nav-dropdown-items">
                    <ul>
                        <li class="nav-item">
                            <security-trimming asp-action="Index" asp-controller="Locations" asp-area="UserPanel">
                                <a class="nav-link" asp-action="Index" asp-controller="Locations" asp-area="UserPanel">
                                    <i class="ni ni-settings-gear-65 text-suceess"></i> تعریف مکان
                                </a>
                            </security-trimming>
                        </li>
                    </ul>
                </ul>
            </li>
        </ul>
    </ul>
</li>